---
# TODO: this doesn't seem to shutdown correctly
# - service: name=tinc state=stopped

- name: "Cleanup hosts file"
  lineinfile: dest=/etc/hosts regexp='.*\.{{ tinc_netname }}$' state=absent

- file: path=/etc/tinc/{{ tinc_netname }}/ state=absent mode=0755 
- file: path=/etc/service/tinc_{{ tinc_netname }} state=absent

- lineinfile: dest="/etc/tinc/nets.boot" line="{{ tinc_netname }}" state=absent

